### ISSUE TITLE
Random crash MacOS Monterey, M1 Pro MBP

### ISSUE THREAD

**Issue by DAWUD2006** [obsproject/.github#32]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://cdn.discordapp.com/attachments/636682784156549152/1032385176182988930/2022-10-19_20-50-26.tx

### Expected Behavior

I was just running obs not doing anything.

### Current Behavior

“ obs quit unexpectedly “

### Steps to Reproduce

1. I just ran OBS
2.
3.
...

**Comment by DAWUD2006** [comment]
https://discord.com/channels/348973006581923840/636682784156549152/1032387154648780801


https://discord.com/channels/348973006581923840/636682784156549152/1032387154757812277

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Additionally, this is the .github configuration repo for the org, which has nothing to do with OBS itself. Please be mindful where you are submitting things in the future.

Thank you!
